### ISSUE TITLE
Update content on "Medewerkers" and translate to "Meet our team".

### ISSUE THREAD

**Issue by janwerkhoven** [floatplane-dev/huisartspoelstra.nl#9]
New text:

### Physician Assistent

In onze praktijk is een Physician assistent in opleiding werkzaam. Zij wordt onze extra dokter (HBO) voor de overzichtelijke problemen.

### Praktijkondersteuner

Binnen de praktijk houdt de praktijkondersteuner zich bezig met de zorg aan chronisch zieken. Er zijn speciale spreekuren voor Diabetes mellitus, Astma Copd, Hypertensie en Hartfalen. De praktijkondersteuner is deskundig op het gebied van begeleiding en voorlichting en heeft meer tijd voor het bespreken van uw vragen.

### Praktijkondersteuner GGZ

Binnen de praktijk houdt de praktijkondersteuner GGZ zich bezig met de geestelijke gezondheidszorg. Zij is deskundig en biedt begeleiding bij psychische of emotionele klachten.

### Doktersassistente

Voor veel praktische zaken en eenvoudige medische vragen kunt u terecht bij de doktersassistente. Tijdens de openingstijden van de balie, 08.00 tot 10.00 uur en 13.30 tot 15.00 uur, kunt u onder meer bij haar terecht voor:

- Urine-onderzoek
- Zwangerschapstest (kosten 10 euro)
- Injecties
- Verwijderen van hechtingen
- Uitspuiten van de oren
- Uitstrijkjes
- ECG

Naast Frank Poelstra zijn er 3 zelfstandige huisartsen werkzaam in de praktijk.

**Comment by codelikeshuwen** [comment]
Please see below translated version and confirm it is good to go. 

************************************************************************

Physician Assistant
Our clinic has a Physician Assistant in training. She will be our extra doctor for any manageable problems.

Practice Assistant
Within the clinic, the Practice Assistant specialises in the care of chronic diseases. There are special consultation hours for Diabetes mellitus, Asthma Copd, Hypertension and Heart failure. The practice nurse is an expert in the field, she can provide more guidance, and information and has more time to discuss your questions.

Practice Nurse GGZ
Within the clinic, the GGZ Practice Nurse is involved in mental health care. She is an expert and offers consultation for psychological or emotional complaints.

Doctor's Assistant
You can contact the Doctor's Assistant for many practical matters and simple medical questions. 
During the opening hours of the desk, 8 a.m. to 10 a.m. and 1:30 p.m. to 3 p.m., 

You can contact her for:

- Urinalysis
- Pregnancy test (cost 10 euros)
- Injections
- Suture removal
- Spraying the ears
- Smears
- EKG

In addition to Frank Poelstra, there are 3 independent general practitioners working in the practice.

**Comment by janwerkhoven** [comment]
Done and live in production. 👌🏻
